sudo: required
notifications:
  email: false
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f73069fb71a8_key -iv $encrypted_f73069fb71a8_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker build -t timcole.me-api .
- docker build -t timcole.me web/
- docker run -d --name api timcole.me-api
- docker run -d --name web timcole.me
- docker ps -a
script:
- docker tag timcole.me-api:latest $DOCKER_HUB_USERNAME/timcole.me-api:production
- docker tag timcole.me:latest $DOCKER_HUB_USERNAME/timcole.me:production
- docker push $DOCKER_HUB_USERNAME/timcole.me-api:production
- docker push $DOCKER_HUB_USERNAME/timcole.me:production
after_script:
- docker rm -f app
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key
    tim@pepega.tcole.me './deploy.sh'
  on:
    branch: master
env:
  global:
  - secure: FWwjKvCuakUCxGAvTDVV3qb5HSmV6hUMTZR63aH4lXUAF2fWf+96qUmoaCVFSyq7dnX7ybcNdM8W55liCruBcdrfTVpN4OKC+hir+7s/2tr8SDVrPT0xBnvg88bdMUPzYt66tBxDCCRiXCJS7PXlt+q71FYWvAQCGkrFUPh+bFANgh14GcRS9REcS3sqXSg4xQ048Uc4duiR4EU/AKWaRSGnrP8LLIBxwfoci/08/XJCfUv3neiysZwbPIF6fanM09XTzRIDsl4I8DdlSRhObcNQTeVCYLxSKC6+4VcO+jebZX6mW6L9WG2zpsJmpIMSgGOnehPdKGvXmk5x1QcGmoKbr5az2ihrcZCzXLc49/dU5G/oUH/3CyjXdXx8Ks+VwbXz+t9tp865DPi4JsfZpGaFNU5jBRudmTo52a1zLZzj+GeJs/8+TnHDmRLMKDtnGl5SOEo6wIcfiSBHtrOJ0W5/zaWPbc9hGXM6WxQB7GnEczEWdT5bdo/X97TWCEz8TlLP0qHqhetPp1+c+6Uh6yS/QVEpsitH3LnhzT6qASsjVQUf/0THs5Diseabikkg4Qn05gHjhvWm8BlZbElFDDMNkueiGP4Z9HXs/VUL01xY+a+NqtkzY5h7rPHLmFAutFlIY80dB8pItO1V2PTeVIJpOHIJwQ6IFHflE19h0Rs=
  - secure: XjjrFo6zWEouk1fhd+ApO7drMLnNt1FRYw1QJ+4K2E1aV+s/O4eqRqPxDHrsG9j2lVnYR0cN4WMM6+Etk92dxygMDOjLwAjKk//1xL2D3Yw/WT4ah8489hqZkt4iKjvCpnl+eDmj9vyNasyqK8ORIUaRPZdbKyjAqRpVUheqocoWjEC1BZUDu4ILqDr4zo5Tb1PwLAbjnHMYGtE9eviBJXzZVqgBfV+ZP9HEjMixU6pGpNpGG+ZHY3lxsVqyHAgZfiZTRU3PUVudWWTOfmgbD+t0AFx2FCZwRuN1ifpMzG2cNW1Ql7gfKSov0+NoMM/boFJQTtFmCQW9gfmXaLnIJXkIvhvTcFHDijN1EXyZs/NvuFdujEnyn3Ezyxft2UVVDCkJCw/qa46ufckwp4emJ3IiGVEG6jOJT+UM5K9M4OHU0+zGlAnVDpk4VzZ4go+EarHhCgMmjvuy+61bdHGVKw0n0nTOFQShVdsTdpJdfSvStKJW37UpVQIbHHaTo/FyNHD6A0sdMA6bA0u0wwJZzAvO7rklNvSf1y1LXH7mDkUd4u2N+XFOhaprO+u04K3QNYsfUUYI+UBicwO0use3YN9kSXRl3Yo7T2aGi06TTEaTtX8/UtkRe7cvDdGUW9DGqL9eGrfwjfvKdDo95bA636UAMm+nFT0Fa0UYnFLciyQ=
